from __future__ import annotations

from typing import Any


MODEL_BLUEPRINTS: list[dict[str, Any]] = [
    {"id": "dual_path_gated_low_rank", "status": "implemented", "category": "architecture_program", "paper_family": "compact_architecture", "change_level": 2, "role": "Dual encoder with input-conditioned gating and a low-rank target-gene head.", "requires": ["tabular_features"], "implementation_notes": "Already implemented as a generated node-local PyTorch model.", "acceptance": ["Defines GeneratedModel(spec)", "Forward returns [batch, n_targets, n_classes] logits"]},
    {"id": "mixture_of_experts", "status": "implemented", "category": "fusion", "paper_family": "multimodal_fusion", "change_level": 4, "role": "Compact router over several MLP experts for perturbation feature regimes.", "requires": ["tabular_features"], "implementation_notes": "Already implemented as a generated node-local PyTorch model.", "acceptance": ["Defines GeneratedModel(spec)", "Forward returns [batch, n_targets, n_classes] logits"]},
    {"id": "target_gene_embedding_bilinear", "status": "implemented", "category": "foundation_model_fusion", "paper_family": "target_gene_aware_gene_embedding", "change_level": 5, "role": "Use a frozen target-gene embedding table plus perturbation/context features to score each DEG target through a bilinear factorized head.", "requires": ["artifact_manifest", "target_gene_embeddings", "perturbation_context_features"], "implementation_notes": "Executable through the built-in model_type target_aware_bilinear. Requires scripts/build_target_gene_artifact.py to create data_dir/artifact_manifest.json and target_gene_embeddings.npz. This is the first repo-supported route that explicitly uses both perturbed-gene/context features and target-gene artifact geometry.", "acceptance": ["Uses model.artifact_manifest_path", "Loads target_gene_embeddings from artifact_manifest.json", "Does not fabricate missing target-gene embeddings", "Forward returns [batch, n_targets, n_classes] logits"]},
    {"id": "film_conditioned_residual", "status": "planned", "category": "fusion", "paper_family": "conditional_computation", "change_level": 4, "role": "Residual blocks modulated by the original perturbation vector.", "requires": ["tabular_features"], "implementation_notes": "Implement FiLM-style residual blocks. Use the input vector to generate gamma/beta modulation for hidden residual layers.", "acceptance": ["No external data required", "Defines GeneratedModel(spec)", "Uses spec.input_dim, hidden_dim, depth, dropout, n_targets, n_classes", "Forward returns [batch, n_targets, n_classes] logits"]},
    {"id": "target_factor_router", "status": "planned", "category": "prediction_head", "paper_family": "target_gene_head", "change_level": 2, "role": "Route-conditioned low-rank target-gene factor head.", "requires": ["tabular_features"], "implementation_notes": "Implement a compact encoder, a route/context projection, and target-gene factors that combine with rank logits.", "acceptance": ["No external data required", "Defines GeneratedModel(spec)", "Keeps parameter count modest", "Forward returns [batch, n_targets, n_classes] logits"]},
    {"id": "learned_perturbation_embedding", "status": "planned", "category": "perturbation_representation", "paper_family": "perturbation_embedding", "change_level": 3, "role": "Replace or augment one-hot perturbation features with learned perturbation/gene embeddings.", "requires": ["perturbation_ids_or_gene_ids"], "implementation_notes": "Use existing perturbation/gene identifiers if present. If not available, record missing metadata rather than altering splits.", "acceptance": ["Documents perturbation id source", "Does not alter train/validation/test split", "Defines fallback if ids are unavailable"]},
    {"id": "gene_embedding_adapter", "status": "planned", "category": "biological_prior", "paper_family": "gene_embedding", "change_level": 3, "role": "Learn or load gene embeddings and condition target heads on gene identity.", "requires": ["gene_ids"], "implementation_notes": "Requires a target-gene id list or embedding table before it can be executable.", "acceptance": ["Documents required gene metadata", "Does not alter train/val/test split"]},
    {"id": "esm2_gene_projection", "status": "implemented", "category": "foundation_model_fusion", "paper_family": "protein_language_model", "change_level": 5, "role": "Project frozen ESM2 protein embeddings into the perturbation-response predictor.", "requires": ["protein_sequences_or_esm2_embeddings"], "implementation_notes": "Implemented as a compact two-branch projection over the repo-built ESM2 feature dataset. The proposal switches to data/cell_lines/k562_concat_esm2_gene_embedding when needed, where the last 1280 input features are perturbation-side ESM2_D1280 embeddings.", "acceptance": ["Documents ESM2 artifact source", "Uses perturbation-side ESM2 features from the audited dataset", "Keeps embeddings frozen by default", "Forward returns [batch, n_targets, n_classes] logits"]},
    {"id": "aido_embedding_fusion", "status": "planned", "category": "foundation_model_fusion", "paper_family": "biological_foundation_model", "change_level": 5, "role": "Fuse AIDO-style biological foundation embeddings with perturbation and expression features.", "requires": ["aido_embeddings"], "implementation_notes": "Requires precomputed AIDO embeddings or an approved loader. Missing artifacts must be reported explicitly.", "acceptance": ["Documents AIDO artifact source", "Does not silently substitute random embeddings", "Keeps large foundation model frozen unless task allows fine-tuning"]},
    {"id": "scfoundation_cell_encoder", "status": "planned", "category": "foundation_model_fusion", "paper_family": "single_cell_foundation_model", "change_level": 5, "role": "Use a frozen scFoundation-style encoder or precomputed cell-state embedding as the expression encoder.", "requires": ["scfoundation_embeddings_or_encoder"], "implementation_notes": "Prefer precomputed embeddings. Do not download or train a large single-cell foundation model without user approval.", "acceptance": ["Documents scFoundation artifact source", "Preserves split semantics", "Defines fallback to expression encoder if unavailable"]},
    {"id": "ppi_graph_message_passing", "status": "implemented", "category": "biological_prior", "paper_family": "graph_prior", "change_level": 5, "role": "Use a STRING/PPI-like graph prior for target-gene message passing.", "requires": ["gene_graph"], "implementation_notes": "Implemented as a node-local compact STRING graph smoother. Requires data/artifacts/string/k562_target_graph_edges.tsv and the data split target_genes. The model predicts target-level logits and mixes them over the normalized target-gene STRING adjacency; if the graph artifact is absent, strict search must acquire it rather than fake edges.", "acceptance": ["Documents graph source", "Loads STRING edge TSV through spec.artifacts", "Handles target genes absent from graph with self-loops", "Forward returns [batch, n_targets, n_classes] logits"]},
    {"id": "string_gnn_perturbation_propagator", "status": "implemented", "category": "biological_prior", "paper_family": "graph_prior", "change_level": 5, "role": "Propagate perturbation signal through a STRING-like gene interaction graph before prediction.", "requires": ["string_graph_edges", "gene_ids"], "implementation_notes": "Implemented as a compact STRING graph propagation node using the real K562 STRING edge artifact. It builds target adjacency from data/artifacts/string/k562_target_graph_edges.tsv and propagates target logits without fabricating missing edges.", "acceptance": ["Documents STRING graph artifact", "Handles genes absent from graph with self-loops", "Does not fabricate edges", "Forward returns [batch, n_targets, n_classes] logits"]},
    {"id": "pathway_pooling_encoder", "status": "implemented", "category": "biological_prior", "paper_family": "pathway_prior", "change_level": 5, "role": "Pool target genes through pathway memberships before DEG classification.", "requires": ["pathway_memberships"], "implementation_notes": "Implemented as a node-local Reactome pathway pooling head. Requires data/artifacts/pathways/k562_target_pathway_membership.npz aligned to split target_genes. Strict search must acquire/build the real pathway artifact before this blueprint is selected.", "acceptance": ["Documents Reactome source", "Loads pathway membership matrix through spec.artifacts", "Records pathway and target-gene coverage", "Forward returns [batch, n_targets, n_classes] logits"]},
    {"id": "cross_attention_gene_perturbation", "status": "planned", "category": "fusion", "paper_family": "multimodal_fusion", "change_level": 4, "role": "Cross-attend target-gene tokens against perturbation/context tokens.", "requires": ["target_gene_embeddings", "perturbation_gene_embeddings_or_context_tokens"], "implementation_notes": "Use artifact_manifest.json when available. Target tokens should come from real ESM2/AIDO/scFoundation artifacts or a documented learnable ablation; do not call a random table a foundation-model artifact.", "acceptance": ["Defines attention dimensions", "Uses target-gene tokens explicitly", "Forward returns target-level class logits"]},
    {"id": "gated_multimodal_fusion", "status": "planned", "category": "fusion", "paper_family": "multimodal_fusion", "change_level": 4, "role": "Fuse cell-state, perturbation, and optional prior embeddings through learned gates.", "requires": ["tabular_features"], "implementation_notes": "Start with available features. If optional embeddings are absent, record which branches were inactive.", "acceptance": ["Documents active modalities", "Defines GeneratedModel(spec)", "Forward returns [batch, n_targets, n_classes] logits"]},
    {"id": "bilinear_gene_perturbation_fusion", "status": "planned", "category": "fusion", "paper_family": "multimodal_fusion", "change_level": 4, "role": "Use bilinear interactions between perturbation context and target-gene factors.", "requires": ["tabular_features", "target_gene_factors"], "implementation_notes": "Implement a compact bilinear or factorized interaction to avoid excessive parameters.", "acceptance": ["Keeps parameter count modest", "Documents interaction rank"]},
    {"id": "class_balanced_deg_classifier", "status": "planned", "category": "prediction_head", "paper_family": "classification_head", "change_level": 2, "role": "Use class-balanced target-level DEG classification with explicit imbalance handling.", "requires": ["class_distribution"], "implementation_notes": "May use weighted loss or calibrated logits. Must not tune on test set.", "acceptance": ["Documents class weights or calibration method", "Reports Macro-F1"]},
    {"id": "uncertainty_calibrated_head", "status": "planned", "category": "prediction_head", "paper_family": "calibration", "change_level": 2, "role": "Add uncertainty or calibration-aware prediction head for DEG labels.", "requires": ["tabular_features"], "implementation_notes": "Keep calibration validation-only. Do not optimize thresholds on test labels.", "acceptance": ["Documents calibration metric", "Preserves validation reward semantics"]},
    {"id": "selective_adapter_finetune", "status": "planned", "category": "fine_tuning", "paper_family": "selective_finetuning", "change_level": 5, "role": "Freeze a base encoder and train small adapters/LoRA-style modules.", "requires": ["pretrained_encoder"], "implementation_notes": "Requires a pretrained encoder. Generate a request unless the encoder is already present in the repo.", "acceptance": ["Documents frozen/trainable parameter groups", "Does not silently train a huge model"]},
    {"id": "focal_loss_training_strategy", "status": "planned", "category": "training_strategy", "paper_family": "optimization", "change_level": 1, "role": "Use focal loss or related imbalance-aware training for hard DEG classes.", "requires": ["class_distribution"], "implementation_notes": "This is a Level 1 training-strategy node. Do not count it as architecture discovery.", "acceptance": ["Documents gamma/alpha", "Reports whether improvement is training-only"]},
    {"id": "multi_task_cellline_conditioning", "status": "planned", "category": "multi_cellline", "paper_family": "multi_context_conditioning", "change_level": 4, "role": "Condition predictions on cell-line identity for multi-cell-line experiments.", "requires": ["multiple_cell_lines"], "implementation_notes": "Requires multiple cell lines and a cell-line id field; not suitable for a one-cell-line run unless used as a no-op ablation.", "acceptance": ["Documents cell-line metadata", "Preserves per-cell-line splits"]},
]


def blueprints(status: str | None = None) -> list[dict[str, Any]]:
    if status is None:
        return list(MODEL_BLUEPRINTS)
    return [item for item in MODEL_BLUEPRINTS if item["status"] == status]


def implemented_blueprint_ids() -> list[str]:
    return [item["id"] for item in blueprints("implemented")]


def selectable_blueprint_ids(include_planned: bool = False) -> list[str]:
    if include_planned:
        return [item["id"] for item in MODEL_BLUEPRINTS if item["status"] in {"implemented", "planned"}]
    return implemented_blueprint_ids()


def blueprint_by_id(blueprint_id: str) -> dict[str, Any]:
    for item in MODEL_BLUEPRINTS:
        if item["id"] == blueprint_id:
            return item
    raise KeyError(f"unknown model blueprint {blueprint_id!r}")
